version: 2.1

jobs:
  playwright-test:
    docker:
      - image: pw-jammy-development
    parallelism: 4
    steps:
      - run:
          name: Run Playwright tests
          command: |
            SHARD="$((${CIRCLE_NODE_INDEX}+1))"
            npx playwright test -- --shard=${SHARD}/${CIRCLE_NODE_TOTAL}

workflows:
  version: 2
  playwright-tests:
    jobs:
      - playwright-test
