version: 2.1

jobs:
  test_shard_1:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Create all-blob-reports directory
          command: mkdir -p all-blob-reports
      - run:
          name: Install dependencies and run tests - Shard 1
          command: |
            npm ci
            npx playwright install-deps
            npx playwright test --shard=1/4
      - run:
          name: Store Blob report - Shard 1
          command: |
            mv blob-report/* all-blob-reports
            zip -r /tmp/workspace/blob-report-shard-1.zip all-blob-reports/*

  test_shard_2:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Create all-blob-reports directory
          command: mkdir -p all-blob-reports
      - run:
          name: Install dependencies and run tests - Shard 2
          command: |
            npm ci
            npx playwright install-deps
            npx playwright test --shard=2/4
      - run:
          name: Store Blob report - Shard 2
          command: |
            mv blob-report/* all-blob-reports
            zip -r /tmp/workspace/blob-report-shard-2.zip all-blob-reports/*

  test_shard_3:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Create all-blob-reports directory
          command: mkdir -p all-blob-reports
      - run:
          name: Install dependencies and run tests - Shard 3
          command: |
            npm ci
            npx playwright install-deps
            npx playwright test --shard=3/4
      - run:
          name: Store Blob report - Shard 3
          command: |
            mv blob-report/* all-blob-reports
            zip -r /tmp/workspace/blob-report-shard-3.zip all-blob-reports/*

  test_shard_4:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Create all-blob-reports directory
          command: mkdir -p all-blob-reports
      - run:
          name: Install dependencies and run tests - Shard 4
          command: |
            npm ci
            npx playwright install-deps
            npx playwright test --shard=4/4
      - run:
          name: Store Blob report - Shard 4
          command: |
            mv blob-report/* all-blob-reports
            zip -r /tmp/workspace/blob-report-shard-4.zip all-blob-reports/*

  merge_reports:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Merge Blob reports
          command: |
            npx playwright merge-reports --reporter html ./all-blob-reports

workflows:
  version: 2
  test_and_merge:
    jobs:
      - test_shard_1
      - test_shard_2
      - test_shard_3
      - test_shard_4
      - merge_reports:
          requires:
            - test_shard_1
            - test_shard_2
            - test_shard_3
            - test_shard_4
