version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci
            npx playwright install-deps

  test_shard:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Run Playwright tests
          command: npx playwright test --shard=$SHARD/4
      - run:
          name: Store Blob report
          command: mv blob-report /tmp/blob-report-shard-$SHARD

  merge_reports:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Merge Blob reports
          command: |
            mkdir -p all-blob-reports
            cp /tmp/blob-report-shard-*/* all-blob-reports/
            npx playwright merge-reports --reporter html ./all-blob-reports

workflows:
  version: 2
  test_and_merge:
    jobs:
      - install_dependencies
      - test_shard:
          name: test_shard_1
          environment:
            SHARD: 1
          requires:
            - install_dependencies
      - test_shard:
          name: test_shard_2
          environment:
            SHARD: 2
          requires:
            - install_dependencies
      - test_shard:
          name: test_shard_3
          environment:
            SHARD: 3
          requires:
            - install_dependencies
      - test_shard:
          name: test_shard_4
          environment:
            SHARD: 4
          requires:
            - install_dependencies
      - merge_reports:
          requires:
            - test_shard_1
            - test_shard_2
            - test_shard_3
            - test_shard_4
