version: 2.1

jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:latest
    # Enable parallelism of 3
    parallelism: 3
    steps:
      - checkout
      - run: npm ci && npx playwright install --with-deps
      - run: npx playwright install chrome
      - run:
          name: Run tests with Playwright Shards
          command: |
            SHARD="$((${CIRCLE_NODE_INDEX}+1))"
            npx pwc --key $CURRENTS_RECORD_KEY --project-id bnsqNa --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
            # Store Blob report
            cp -r blob-report /tmp/blob-report-shard-${SHARD}

# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test:
          # Use "currents" CircleCI context to enable access to secrets
          context: currents
