version: 2.1

jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:latest
    # Enable parallelism of 3
    parallelism: 3
    steps:
      - checkout
      - run: npm ci && npx playwright install --with-deps
      - run: npx playwright install chrome
      - run:
          name: Run tests with Playwright Shards
          command: |
            TOTAL_TESTS=24
            SHARD_SIZE=$((TOTAL_TESTS / CIRCLE_NODE_TOTAL))
            START_INDEX=$((SHARD_SIZE * CIRCLE_NODE_INDEX))
            END_INDEX=$((START_INDEX + SHARD_SIZE))
            npx playwright test --workers=$SHARD_SIZE --testMatch="**/*.spec.js" --repeat-each=1 --headful --headed --grep ".*" --project-type=javascript --timeout=30000 --retries=0 --max-failures=0 --output=flaky --video=on --trace=on --reporter=dot --repeat-each=1 --workers=$CIRCLE_NODE_TOTAL --parallel $START_INDEX-$END_INDEX
            # Store Blob report
            cp -r blob-report /tmp/blob-report-shard-${CIRCLE_NODE_INDEX}

# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test:
          # Use "currents" CircleCI context to enable access to secrets
          context: currents
