version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci
            npx playwright install-deps

  test_shard_1:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Run Playwright tests - Shard 1
          command: |
            npx playwright test --shard=1/4
      - run:
          name: Store Blob report - Shard 1
          command: mv blob-report /tmp/blob-report-shard-1

  test_shard_2:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Run Playwright tests - Shard 2
          command: |
            npx playwright test --shard=2/4
      - run:
          name: Store Blob report - Shard 2
          command: mv blob-report /tmp/blob-report-shard-2

  test_shard_3:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Run Playwright tests - Shard 3
          command: |
            npx playwright test --shard=3/4
      - run:
          name: Store Blob report - Shard 3
          command: mv blob-report /tmp/blob-report-shard-3

  test_shard_4:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Run Playwright tests - Shard 4
          command: |
            npx playwright test --shard=4/4
      - run:
          name: Store Blob report - Shard 4
          command: mv blob-report /tmp/blob-report-shard-4

workflows:
  version: 2
  test_and_merge:
    jobs:
      - install_dependencies
      - test_shard_1:
          name: Test Shard 1
          requires:
            - install_dependencies
      - test_shard_2:
          name: Test Shard 2
          requires:
            - install_dependencies
      - test_shard_3:
          name: Test Shard 3
          requires:
            - install_dependencies
      - test_shard_4:
          name: Test Shard 4
          requires:
            - install_dependencies
