version: 2.1

jobs:
  test_shard_1:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Playwright and browsers
          command: npm ci && npx playwright install --with-deps
      - run:
          name: Run Playwright tests - Shard 1
          command: npx playwright test --shard=1/4
      - run:
          name: Store Blob report
          command: mv blob-report /tmp/blob-report-shard-1

  test_shard_2:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Playwright and browsers
          command: npm ci && npx playwright install --with-deps
      - run:
          name: Run Playwright tests - Shard 2
          command: npx playwright test --shard=2/4
      - run:
          name: Store Blob report
          command: mv blob-report /tmp/blob-report-shard-2

  test_shard_3:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Playwright and browsers
          command: npm ci && npx playwright install --with-deps
      - run:
          name: Run Playwright tests - Shard 3
          command: npx playwright test --shard=3/4
      - run:
          name: Store Blob report
          command: mv blob-report /tmp/blob-report-shard-3

  test_shard_4:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Playwright and browsers
          command: npm ci && npx playwright install --with-deps
      - run:
          name: Run Playwright tests - Shard 4
          command: npx playwright test --shard=4/4
      - run:
          name: Store Blob report
          command: mv blob-report /tmp/blob-report-shard-4

  merge_reports:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Merge Blob reports
          command: |
            mkdir -p all-blob-reports
            cp /tmp/blob-report-shard-*/* all-blob-reports/
            npx playwright merge-reports --reporter html ./all-blob-reports

workflows:
  version: 2
  test_and_merge:
    jobs:
      - test_shard_1
      - test_shard_2
      - test_shard_3
      - test_shard_4
      - merge_reports:
          requires:
            - test_shard_1
            - test_shard_2
            - test_shard_3
            - test_shard_4
