version: 2.1

# Define a reusable set of steps for installing dependencies and running tests
# This will be used by all shard jobs
defaults: &test_steps
  - checkout
  - run:
      name: Install dependencies
      command: |
        npm ci
        npx playwright install-deps
  - run:
      name: Run Playwright tests
      command: npx playwright test --shard={shard}/4
  - run:
      name: Store Blob report
      command: mv blob-report /tmp/blob-report-shard-{shard}

jobs:
  # Shard jobs using the defined set of steps
  test_shard_1:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps: *test_steps
      # Replace '{shard}' with '1' in the aliased steps
      - run: *test_steps
        command: | 
          npm ci
          npx playwright install-deps
          npx playwright test --shard=1/4
      - run: *test_steps
        command: mv blob-report /tmp/blob-report-shard-1

  test_shard_2:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps: *test_steps
      # Replace '{shard}' with '2' in the aliased steps
      - run: *test_steps
        command: | 
          npm ci
          npx playwright install-deps
          npx playwright test --shard=2/4
      - run: *test_steps
        command: mv blob-report /tmp/blob-report-shard-2

  test_shard_3:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps: *test_steps
      # Replace '{shard}' with '3' in the aliased steps
      - run: *test_steps
        command: | 
          npm ci
          npx playwright install-deps
          npx playwright test --shard=3/4
      - run: *test_steps
        command: mv blob-report /tmp/blob-report-shard-3

  test_shard_4:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps: *test_steps
      # Replace '{shard}' with '4' in the aliased steps
      - run: *test_steps
        command: | 
          npm ci
          npx playwright install-deps
          npx playwright test --shard=4/4
      - run: *test_steps
        command: mv blob-report /tmp/blob-report-shard-4

  # Job for merging reports
  merge_reports:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - checkout
      - run:
          name: Merge Blob reports
          command: |
            mkdir -p all-blob-reports
            cp /tmp/blob-report-shard-*/* all-blob-reports/
            npx playwright merge-reports --reporter html ./all-blob-reports

workflows:
  version: 2
  test_and_merge:
    jobs:
      - test_shard_1
      - test_shard_2
      - test_shard_3
      - test_shard_4
      - merge_reports:
          requires:
            - test_shard_1
            - test_shard_2
            - test_shard_3
            - test_shard_4
